version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    working_dir: /home/www-user/site
    volumes:
      - ./src:/home/www-user/site
    networks:
      - www-user

  mysql:
    image: mysql:5.7.29
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - www-user

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/home/www-user/site
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www-user
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    ports:
      - "8081:80"
    volumes:
      - /sessions
    networks: 
      - www-user

networks:
  www-user:
    driver: bridge
